import { Plus_Jakarta_Sans, Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/Components/Navbar";
import { ToastContainer } from "react-toastify";

const sansHeading = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-heading",
});

const sansBody = Inter({
  subsets: ["latin"],
  variable: "--font-body",
});

export const metadata = {
  title: "Online ticket booking platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${sansBody.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning={true}>
         <Navbar/>
        <main className="container mx-auto">
          {children}
        </main>
 <ToastContainer position="top-center" />

      </body>
    </html>
  );
}
